#!/bin/bash

kubectl delete namespaces dev 
kubectl delete pv shipyard-db-persistentvolume 
kubectl delete pv shipyard-grafana-persistentvolume 

minikube ssh -- sudo rm -rf /data/shipyard-db-data /data/shipyard-grafana-data
