#!/bin/bash

# TODO(sam): add a context
#ARGS="--context=democart --namespace=dev"
ARGS="--namespace=dev"

kubectl $ARGS apply -f "dev/namespace.yml"
kubectl $ARGS apply -f "dev/persistentvolumes.yml"
kubectl $ARGS apply -f "dev/secret.yml"
kubectl $ARGS apply -f "dev"
